import type { Metadata } from "next";
import { Nunito_Sans } from "next/font/google";
import "./globals.css";
import Providers from "@/provider";
import Head from "@/components/Head";

const font = Nunito_Sans({ subsets: ["latin"], weight: ["300", "600", "800"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${font.className}  
          min-h-screen text-dark-blue-text dark:text-white`}
      >
        <Providers>
          <div className="dark:bg-very-dark-blue min-h-screen bg-very-light-gray">
            <Head />
            {children}
          </div>
        </Providers>
      </body>
    </html>
  );
}
